# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 
  host: <%= ENV['DB_HOST'] || 'localhost' %>

development:
  <<: *default
  database: twilio_flex_auth_server_development

test:
  <<: *default
  database: twilio_flex_auth_server_test

production:
  <<: *default
  database: twilio_flex_auth_server_production
  username: twilio_flex_auth_server
  password: <%= ENV['TWILIO_FLEX_AUTH_SERVER_DATABASE_PASSWORD'] %>
